[package]
name = "chromox-app"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.9.0", features = [] }

[dependencies]
tauri = { version = "2.9.0", features = ["devtools", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
